- config/docker-host-nginx.conf
- config/nginx.conf
- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/track.html
- sass/app.scss
- socketio/server.js
* Added a "Move to Top" button to each track in the queue
* When playing a song, move it to the bottom of the queue
* Fix the user reported for upvote/downvote notifications
* Fix order of Nginx servers to default to the working instance for dev copies
> Add "Move to Top", move played songs to bottom, fix Nginx config, fix upvote/downvote users

- bower.json
- config/nginx.conf
- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/filters.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/room-queue.html
- lstn/static/partials/directives/track.html
- lstn/templates/index.html
- package.json
- sass/app.scss
- socketio/server.js
This includes what's in PR #72 so merge it first.
This PR adds timestamps to the chat history:
> Chat timestamps

- config/ec2-user-data.txt
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/chat-message.html
- lstn/static/partials/directives/room-queue.html
- lstn/static/partials/room.html
- socketio/server.js
Fixed region in ec2-user-data. I apparently set everything up in west.
Moved Rdio alerts to the alert system (Fixes #69)
Killed local scope variables as we were already using ```$scope```.
Add skip notifications to the chat system and cleaned that up (Fixes #68)
> Fix region in ec2-user-data. Moved rdio alerts to alert system #69. Killed local scope variables.

- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/playing-info.html
- lstn/static/partials/directives/room-queue.html
- sass/app.scss
> Add a canStream warning to help with #59 Added unseen chat message badge #51

- Gruntfile.coffee
- lstn/templates/index.html
- package.json
Automatically inject bower JS files into index.html by running ```grunt wiredep``` or just ```grunt```
> added wiredep and usemin support.

- .jshintrc
- Gruntfile.coffee
- config/nginx.conf
- lstn/static/js/directives.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/room-queue.html
- socketio/config.json
- socketio/server.js
Cleans up the nginx config to work with the new grunt setup.
Fixes the chat message enter handling when a mentioMenu is open. Fixes #108.
> Add dist and static to try_files paths. Fix mentioMenu enter button #108.

- .jshintrc
- Gruntfile.coffee
- config/nginx.conf
- lstn/static/css/app.css
- lstn/static/js/app.js
- lstn/static/js/directives.js
- lstn/static/js/filters.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/room-queue.html
- lstn/static/partials/directives/track.html
- lstn/static/sass/app.scss
- socketio/config.json
- socketio/server.js
This isn't going into master because the hover for "Move to Top" is hella busted.
Includes #111
> Implement track duration indicator

- lstn/__init__.py
- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/album.html
- lstn/static/partials/directives/artist.html
- lstn/static/partials/directives/chat-message.html
- lstn/static/partials/directives/more-music.html
- lstn/static/partials/directives/music-categories.html
- lstn/static/partials/directives/music-search.html
- lstn/static/partials/directives/playing-image.html
- lstn/static/partials/directives/playing-info.html
- lstn/static/partials/directives/room-control-downvote.html
- lstn/static/partials/directives/room-control-skip.html
- lstn/static/partials/directives/room-control-upvote.html
- lstn/static/partials/directives/room-control-volume.html
- lstn/static/partials/directives/room-playing.html
- lstn/static/partials/directives/room-queue.html
- lstn/static/partials/directives/track-list.html
- lstn/static/partials/directives/track.html
- lstn/static/partials/room.html
- lstn/static/sass/app.scss
- lstn/views/api/album.py
- lstn/views/api/artist.py
- lstn/views/api/user.py
- socketio/server.js
I renamed 'song' to 'track' everywhere because now that we're supporting albums and artists in certain contexts, it made less sense. Also, 'track' is the term Rdio uses and I like it better than song.
> Start implementing the music search tab. Rename song references to track.

- lstn/static/css/app.css
- lstn/static/js/directives.js
- lstn/static/sass/app.scss
> song.track fix, playing info UI

- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/album.html
- lstn/static/partials/directives/artist.html
- lstn/static/partials/directives/category.html
- lstn/static/partials/directives/more-music.html
- lstn/static/partials/directives/music-search.html
- lstn/static/partials/directives/playlist.html
- lstn/static/partials/directives/room-queue.html
- lstn/static/partials/directives/track-list.html
- lstn/static/partials/directives/track.html
- lstn/static/sass/_variables.scss
- lstn/static/sass/app.scss
- lstn/templates/layout.html
I'm still working on drilling down into playlists but it's close.
> Add support for search and playlist drilldown menus (w/ carousels)

- lstn/static/js/controllers.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/album.html
- lstn/static/partials/directives/artist.html
- lstn/static/partials/directives/category.html
- lstn/static/partials/directives/playlist.html
- lstn/static/partials/directives/track.html
- lstn/templates/layout.html
> Add GA, Fix alert system (#151), replace title with tooltips

- lstn/static/css/app.css
- lstn/static/js/templates.js
- lstn/static/partials/directives/room-roster.html
- lstn/static/sass/app.scss
> Added current broadcaster indicator

- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/filters.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/chat-message.html
- lstn/static/partials/directives/music-search.html
- lstn/static/partials/directives/room-activity.html
- lstn/static/partials/room.html
- lstn/static/sass/_variables.scss
- lstn/static/sass/app.scss
- lstn/templates/layout.html
- socketio/server.js
Fixes #1, #131, and #151. Also gets chat working again.
> Adds links to room activity (#1), Fix the alert system (#151), style the room activity (#131), Fix chat

- lstn/models/__init__.py
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/category.html
- lstn/static/partials/directives/music-categories.html
- lstn/static/partials/directives/music-search.html
- lstn/static/partials/directives/playlist-type.html
Fixes #132
This also allows me to start working on loading stations and to dive down to any level easily
> Added a playlists level above playlist types. Made the carousel system use a type map for slide navigation. Fixes #132

- bower.json
- lstn/static/js/controllers.js
- lstn/static/js/services.js
Fixes #92 
As mentioned in #92, the Gist referenced seems tied around the test swf file they must have. To avoid adding an additional SWF file, I'm setting a scope flag to true when the rdio ready callback is called. Then I set a timeout to check if the value is still the same after 5 seconds. It's a little fragile (and dependent on it taking 5 seconds or less to get the rdio SWF file), so I'm open to suggestions.
Also, (allthethings) whitespace, and it didn't look like we were passing Alert into the RoomController (even though we're referencing it).
> Add Basic Flash Detection (Fixes #92 )

- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/playing-info.html
- lstn/static/partials/directives/room-controls.html
- lstn/static/sass/app.scss
> Get Now Playing/Playback controls to better match the mockup

- lstn/static/js/controllers.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/room-control-skip.html
Includes #171 
We were incorrectly referencing `skipSong` instead of `skipTrack`, causing the skip button to fail silently. I've updated the reference.
> Fix the Skip Button

- lstn/__init__.py
- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/music-categories.html
- lstn/static/partials/directives/station-type.html
- lstn/static/partials/directives/station.html
- lstn/static/sass/app.scss
- lstn/views/api/album.py
- lstn/views/api/artist.py
- lstn/views/api/playlist.py
- lstn/views/api/station.py
- lstn/views/api/user.py
There are still some station types that don't pull correctly so I'm working on that. I also plan on eventually refactoring and DRYing up the slides and directives around the carousel code.
> First pass at station support

- Gruntfile.coffee
- bower.json
- lstn/static/css/app.css
- lstn/static/js/controllers.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/help.html
- lstn/static/partials/index.html
- lstn/static/partials/rooms.html
- lstn/static/sass/app.scss
- lstn/templates/layout.html
- lstn/templates/privacy.html
- lstn/views/site.py
Adds a privacy policy and kills the Rdio name usage. #85
Adds some background coloring to the /rooms page. #136
Adds a better check for the room id an clears the room info in other controllers. #137
Uses Snackbar.js (part of Material UI for Bootstrap) for alert messages. #176
> Starts on Rdio ToS changes (#85). Adds basic styling to /rooms (#136 ). Fixes room name bug (#137). Reworks Alerts (#176)

- lstn/static/css/app.css
- lstn/static/sass/app.scss
> New UI: Finish Flexing All the Things

- lstn/static/css/app.css
- lstn/static/js/templates.js
- lstn/static/partials/directives/track.html
- lstn/static/sass/_variables.scss
- lstn/static/sass/app.scss
Current idea is the drag handle isn't the sole handle for dragging (give users more control), but we at least are now providing context that it's possible.
Fixes #142 and #143
> New UI: Icon Tweaks and Add Drag Handle

- lstn/static/js/controllers.js
- lstn/static/js/directives.js
- lstn/static/js/services.js
This also takes care of clearing open alerts and clearing the currentRoom singleton
Fixes #186
> Start tracking timeouts and promises and clearing them on destroy. Fixes #186

- config/docker-host-nginx.conf
- config/nginx.conf
- lstn/static/js/controllers.js
- lstn/static/js/services.js
- lstn/static/js/templates.js
- lstn/static/partials/directives/playing-info.html
- lstn/static/partials/directives/room-control-upvote.html
Rdio is now only to be used in one place at at time.
> Fix missing evalAsync on Rdio service
